### ISSUE TITLE
Multi-tenancy in modules

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.module.blogs#23]
Hi @sbwalker,

Can you explain how multi-tenancy works with this example?  When I look at the database (00.00.01.sql) script creating the table, I don't see a tenant id? Should I expect one? 

I see the foreign key back to the modules table, is this reference to module id enough to make multi-tenancy work? Also, let's say I extend this example and create a new table for Blog Categories, would that table need to reference back to the Modules table? Or is it sufficient that just one table reference the modules table. (I would probably have a reference between Blogs and Blog Categories).

I've seen some database examples where each table has a reference back to the tenant id (or other key). 

Thanks for any guidance!

**Comment by sbwalker** [comment]
The ModuleId foreign key is the only thing required in order for a module to function properly in the composite UI and support multi-tenancy.
