### ISSUE TITLE
How to Include dependent NuGet packages

### ISSUE THREAD

**Issue by knight1219** [oqtane/oqtane.module.blogs#24]
So I have created a module, created a nuget package for it and it installs fine. One issue is the this package requires other packages from NuGet to function properly and I need to get this files also. How does this work? I See in the IModule implementation the there is a Dependencies setting, is this all I need? Add the names of any packages I need and they will be downloaded and installed as well?

**Comment by ADefWebserver** [comment]
This may help:
http://blazorhelpwebsite.com/Blog/tabid/61/EntryId/4361/Explore-The-Blazor-Oqtane-Blog-Module.aspx

**Comment by knight1219** [comment]
Are there plans to include dependency download/resolution? Seems like adding the raw dll to the package defeats the purpose of using nuget packages.

**Comment by sbwalker** [comment]
In the traditional Microsoft development world you typically use Nuget packages to add low level components to your application in a development environment. When you later deploy your entire application to a production environment, the components are deployed alongwith your application assemblies - they are not deployed using Nuget. 

In the Oqtane model, a module is an application. It may have dependencies on addition components and when you are developing the module, you may choose to download them using Nuget. However when it comes time to deploy your module to production, you need to package your module into an installable artifact. Modules use the Nuget packaging standard for this purpose. A module artifact can then be uploaded interactively to a production environment and the framework knows how to extract its contents to the appropriate locations to complete the integration. Similar to the traditional Microsoft development model, the components are deployed alongwith your module assemblies - they are not deployed using Nuget.

Does this make sense?
